version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: barbershop_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: barbershop_db
    ports:
      - '5432:5432'
    volumes:
      - barbershop_pgdata:/var/lib/postgresql/data

volumes:
  barbershop_pgdata: